### ISSUE TITLE
Tensorflow should be a dependency

### ISSUE THREAD

**Issue by tebeka** [conda-forge/keras-feedstock#17]
The default backend now is tensorflow, it should be a dependency when installing.

**Comment by jakirkham** [comment]
So we can almost always do this. However there is no `tensorflow` build for Windows Python 2.7. So we have to use `theano` there. Also sometimes OS compatibility issues for us to use `theano` instead of `tensorflow` (e.g. old Linux distros).

That said, have added some improvements to PR ( https://github.com/conda-forge/keras-feedstock/pull/25 ), which pull in `tensorflow` whenever possible. Further it will default to using `tensorflow` (except if a user specified config says otherwise). If there are issues though, it falls back to `theano`.
